### ISSUE TITLE
yield rp(options) return undefined

### ISSUE THREAD

**Issue by judin74** [zqingr/node-wda#1]
It worked well until a few days ago. 
However, the yield rp (options) of function(httpdo) now returns undefined.
I do not know the cause.

**Comment by judin74** [comment]
If iphone is wifi connected and port forwarded to iproxy, request-promise(localhost) will return undefined.
The solution is to set connection: keep-alive on the headers.

const options = {
             uri: url,
             method,
             body: payload,
             headers: {
                 'Connection': 'keep-alive',
                 'User-Agent': 'Request-Promise'
             },
             json: true // Automatically parses the JSON string in the response^M
         };

**Comment by zqingr** [comment]
Thanks for your report!
